apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-cert
  namespace: demo-app
spec:
  dnsNames:
    - demo-app-gabrieletupini.ga 
  secretName: frontend-secret
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
